name: Build Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@v10
      with:
        swap-size-mb: 10240

    - name: Checkout main repository
      uses: actions/checkout@v4.1.7
      with:
        repository: mylove90/sm-a245n_14_opensource

    - name: Sync toolchains from GitLab
      run: |
        git clone --depth=1 -b A155F/N https://gitlab.com/mylove90/toolchain.git toolchain
        cd toolchain
        cp -r * ../

    - name: Sync Anykernel3
      run: |
        git clone --depth=1 --branch A15 https://github.com/mylove90/AnyKernel3 AnyKernel3

    - name: Set up build environment
      run: |
        sudo apt update
        sudo apt install -y build-essential bc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libfl-dev
        sudo apt install -y curl git ftp lftp wget libarchive-tools ccache python2 python2-dev
        sudo apt install -y zip unzip tar gzip bzip2 rar unrar

    - name: Build kernel
      run: |
        chmod a+x build_kernel.sh
        bash build_kernel.sh

    - name: Pack AnyKernel3 ZIP
      run: |
        cp -f out/target/product/a24_kor/obj/KERNEL_OBJ/kernel-5.10/arch/arm64/boot/Image.gz ./AnyKernel3/
        cp -f out/target/product/a24_kor/obj/KERNEL_OBJ/*.ko ./AnyKernel3/modules/system/lib/modules/
        mkdir zip
        cd AnyKernel3/
        rm -rf .git .github README.md
        zip -r9 a245n-kernel.zip *
        mv a245n-kernel.zip ../zip/

    - name: Upload AnyKernel3 ZIP
      uses: actions/upload-artifact@v4.3.4
      with:
        name: a245n-kernel.zip
        path: zip/a245n-kernel.zip
